# https://github.com/serverless-components/tencent-layer/blob/master/docs/configure.md
component: layer
name: bgmlist
org: yuangezhizao
app: yuangezhizao
stage: dev

inputs:
  name: '${name}'
  region: ap-beijing
  src:
    src: ../node_modules
    targetDir: /node_modules
  runtimes:
    - Nodejs12.16
